#!/usr/bin/python
#*****************************************************************
# Author: David Bayle
# Contact: contact@davidbayle.com
# This python scripts cheks your ethOS mining rig Hash for Nagios Monitoring
#
# Usage: If the script detects hashrate lower than your threshold, or crashed GPU(s)
# it will start counting up to 5 (5 x 1 min by defaults) and then force reboot.
#
#
# Settings:
# Do not forget to adjust your global minimum hashrate value by rig [rigMinHashRate] to your needs :
# # rigMinHashRate = 110.0
#
# Requirements:
#
# R1) Create a gpu_crashReboot.log file with 0 as value inside and set it with the right permissions :
# (as ethos user:)
# # sudo echo 0 > /usr/lib/nagios/plugins/gpu_crashReboot.log
# # sudo chown nagios:nagios /usr/lib/nagios/plugins/gpu_crashReboot.log
#
# R2) edit Sudoers file using :
# (as ethos user:)
# # sudos -s
# # visudo
#
# and add the following at the end:
# # Nagios NRPE/Check_rig-hash
# nagios ALL=(ALL) NOPASSWD: ALL
#
# Once done, save and quit.
# Script will now be allowed to restart your rig if something goes wrong as explained in Usage section.
# Enjoy ;)
#
#

import os
import sys

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

RETURN_STATE = STATE_OK

rigMinHashRate = 110.0
rigRebootLogFile = "/usr/lib/nagios/plugins/gpu_crashReboot.log"
rigStatusLogFile = "/var/run/ethos/status.file"
rigStatsLogFile = "/var/run/ethos/stats.file"


# ================================   functions  =============================
def PrintOutput(dumpStr):
  print dumpStr


def return_state(state):
  global RETURN_STATE
  RETURN_STATE = state


def ReadStatusFile():
  try:
    # read rig hash rate from ethos status file
    pStatusLogFile = open(rigStatusLogFile, "r")
    returnedStatus = pStatusLogFile.read()
    return returnedStatus
  except:
    print "File read error in - " + rigStatusLogFile


def ReadRigName():
  try:
    # read rig name from ethos stats file
    pStatsLogFile = open(rigStatsLogFile, "r")
    for line in open(rigStatsLogFile, "r"):
      if "rack_loc" in line:
        returnedString = line.split(":", 1)
        returnedName = returnedString[1]
        rName = returnedName.replace("\n", "")
        return rName
  except:
    print "File read error in - " + rigStatsLogFile


def WriteRebootCount(count):
  #print count
  try:
    # writes reboot counter in a file
    pLogFile = open(rigRebootLogFile, "w")
    pLogFile.write("%i" % int(count))
    pLogFile.close()
  except:
    print "File write error in - " + rigRebootLogFile


def ReadRebootCount():
  try:
    # read reboot counter from a file
    pLogFile = open(rigRebootLogFile, "r")
    returnedValue = pLogFile.read(1)
#    print returnedValue
    return returnedValue
  except:
    print "File read error in - " + rigRebootLogFile


def IsNumber(n):
    is_number = True
    try:
        num = float(n)
        # check for "nan" floats
        is_number = num == num   # or use `math.isnan(num)`
    except ValueError:
        is_number = False
    return is_number


#================================ RUN ======================================== #

try:
# try reading status file
    rigStats = ReadStatusFile()
# try reading status file
    rigName = ReadRigName()
# gpu reboot count init
    gpuRebootCount = int(ReadRebootCount())
except:
    PrintOutput("UNKNOWN - Invalid Status File / Reboot counter read")
    return_state(STATE_UNKNOWN)

# extract data
try:
    hashRateData =  rigStats.split(" ", 1)
#    print hashRateData[0]
    hashRate = hashRateData[0]
except:
    PrintOutput("UNKNOWN - Invalid RIG Hashrate reading")
    return_state(STATE_UNKNOWN)


if (IsNumber(hashRateData[0])):

  if (float(hashRate) <= float(rigMinHashRate)):
    PrintOutput("WARNING: RIG HASHRATE LOWER THAN THRESHOLD (" + str(rigMinHashRate) + ") : " + hashRate + " (MH/s)")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    return_state(STATE_WARNING)
    sys.exit(STATE_WARNING)
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER CRASHED FOR 5 MINs : RIG HASHRATE LOWER THAN THRESHOLD (" + str(rigMinHashRate) + ") : " + hashRate + " (MH/s)")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")
      return_state(STATE_CRITICAL)
      sys.exit(STATE_CRITICAL)

  else:
    WriteRebootCount(0)
    PrintOutput("OK - [" + str(rigName) + "] Global Rig hashrate : " + hashRate + " (MH/s) [Threshold: " +str(rigMinHashRate) + "]")
    return_state(STATE_OK)
    sys.exit(STATE_OK)

else:
  if (hashRateData[0].strip() == "gpu" and "clock problem" in hashRateData[1].strip()):
    PrintOutput("WARNING: A GPU CRASHED !!!")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER GPU CRASHED FOR 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")
      return_state(STATE_CRITICAL)
      sys.exit(STATE_CRITICAL)

  if (hashRateData[0].strip() == "possible" and "miner stall" in hashRateData[1].strip()):
    PrintOutput("WARNING: POSSIBLE MINER CRASH !!!")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER GPU CRASHED FOR 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")
      return_state(STATE_CRITICAL)
      sys.exit(STATE_CRITICAL)

  if (hashRateData[0].strip() == "miner" and hashRateData[1].strip() == "started"):
    PrintOutput("WARNING: Miner Starting")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    return_state(STATE_WARNING)
    sys.exit(STATE_WARNING)
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER DIDN'T START IN 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")
      return_state(STATE_CRITICAL)
      sys.exit(STATE_CRITICAL)


